server:
  port: 9001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RegistrationDB
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG
    org.springframework.security.oauth2.server.authorization.config: DEBUG

